plugins {
    id 'fabric-loom' version '1.8-SNAPSHOT'
    id 'maven-publish'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = 'https://maven.fabricmc.net/' }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

    implementation 'com.moandjiezana.toml:toml4j:0.7.2'
    implementation 'org.json:json:20231013'
}

loom {
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java', 'src/fabric/java', 'src/fabric/client/java']
        }
        resources {
            srcDirs = ['src/main/Resources']
        }
    }
}

def fabricModProps = [
        mod_id           : mod_id,
        mod_name         : mod_name,
        mod_version      : mod_version,
        mod_description  : mod_description,
        mod_authors      : mod_authors,
        mod_license      : mod_license,
        minecraft_version: minecraft_version,
        loader_version   : loader_version
]

tasks.named('processResources', ProcessResources).configure {
    inputs.properties(fabricModProps)
    filesMatching('fabric.mod.json') {
        expand(fabricModProps)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
    withSourcesJar()
}

publishing {
    publications {
        create('mavenJava', MavenPublication) {
            artifactId = mod_id
            from components.java
        }
    }

    repositories {
        maven {
            url = layout.buildDirectory.dir('repo')
        }
    }
}
