# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Minecraft / Forge
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

# Mod
mod_id=scs
mod_name=Sync Client Server (SCS)
mod_license=MIT
mod_version=1.1.1
mod_group_id=com.scs
mod_authors=Maeiro(SCS), Place-Boy(MMMMM)
mod_description=Sync Client Server (SCS) keeps client mods and configs in sync with a server pack
