org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.16.10
fabric_api_version=0.92.3+1.20.1

mod_id=scs
mod_name=Sync Client Server (SCS)
mod_license=MIT
mod_version=1.1.1-fabric.1
mod_group_id=com.scs
mod_authors=Maeiro(SCS), Place-Boy(MMMMM)
mod_description=Sync Client Server (SCS) keeps client mods and configs in sync with a server pack
